sonar.projectKey=cp01-devsecops-grupo2
sonar.projectName=CP01 DevSecOps - Grupo 2
sonar.sources=app
sonar.exclusions=**/Dockerfile
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.working.directory=/tmp/cp01-scannerwork

